In [122]:
import numpy as np
import pandas as pd

In [123]:
df_book=pd.read_csv('data/data.csv')

In [124]:
df_book.sample(10)

,isbn13,isbn10,title,subtitle,authors,categories,thumbnail,description,published_year,average_rating,num_pages,ratings_count
6265,9781583421543,1583421548,Rumble Fish,NaN,Marcus Romer;S. E. Hinton,Juvenile Fiction,http://books.google.com/books/content?id=vY9oG...,A two-act play adapted from S. E. Hinton's cla...,2003.0,3.87,135.0,885.0
6770,9781933110455,1933110457,Carly's Sound,NaN,Ali Vali,Fiction,http://books.google.com/books/content?id=vAvDw...,Is passion still possible the second time arou...,2006.0,4.21,212.0,441.0
2525,9780399504334,0399504338,Amphigorey,Fifteen Books,NaN,Comics & Graphic Novels,http://books.google.com/books/content?id=uQe2a...,Fifteen works by the American artist and autho...,1980.0,4.05,220.0,35332.0
1501,9780312289515,0312289510,The Christmas Shoes,NaN,Donna VanLiere,Fiction,http://books.google.com/books/content?id=ISMSv...,"While shopping for gifts on Christmas Eve, Rob...",2001.0,4.23,132.0,31800.0
2790,9780440391548,0440391547,The Turn of the Screw and Daisy Miller,NaN,Henry James,Popular literature,http://books.google.com/books/content?id=OmsIx...,NaN,1983.0,3.62,192.0,940.0
6018,9781558492769,1558492763,Betty Friedan and the Making of The Feminine M...,"The American Left, the Cold War, and Modern Fe...",Daniel Horowitz,Political Science,http://books.google.com/books/content?id=szJCH...,This biography of Betty Friedan traces the dev...,2000.0,3.59,384.0,58.0
405,9780061053665,006105366X,My Soul to Keep,NaN,Tananarive Due,Fiction,http://books.google.com/books/content?id=-5IDA...,"When Jessica marries David, he is everything s...",1998.0,4.18,346.0,3575.0
91,9780007195718,0007195710,Discover Your Destiny with the Monk Who Sold H...,The 7 Stages of Self-Awakening,Robin Sharma,Conduct of life,http://books.google.com/books/content?id=4hVbN...,A potent pathway to self-awakening that will h...,2004.0,3.90,240.0,1956.0
2075,9780375701801,037570180X,Geisha,"The Life, the Voices, the Art",Jodi Cobb;Ian Buruma,Photography,http://books.google.com/books/content?id=GvuAJ...,Looks inside the private world of the geisha t...,1998.0,3.89,128.0,183.0
3173,9780486275505,0486275507,"The Road Not Taken, and Other Poems",NaN,Robert Frost,Poetry,http://books.google.com/books/content?id=CGLcD...,"""Two roads diverged in a wood, and I I took th...",1993.0,4.27,49.0,33004.0

In [125]:
df_book.shape

(6810, 12)

In [126]:
df_book.info()

<class 'pandas.DataFrame'>
RangeIndex: 6810 entries, 0 to 6809
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   isbn13          6810 non-null   int64
 1   isbn10          6810 non-null   str
 2   title           6810 non-null   str
 3   subtitle        2381 non-null   str
 4   authors         6738 non-null   str
 5   categories      6711 non-null   str
 6   thumbnail       6481 non-null   str
 7   description     6548 non-null   str
 8   published_year  6804 non-null   float64
 9   average_rating  6767 non-null   float64
 10  num_pages       6767 non-null   float64
 11  ratings_count   6767 non-null   float64
dtypes: float64(4), int64(1), str(7)
memory usage: 4.3 MB

In [127]:
df_book.isnull().sum()

isbn13               0
isbn10               0
title                0
subtitle          4429
authors             72
categories          99
thumbnail          329
description        262
published_year       6
average_rating      43
num_pages           43
ratings_count       43
dtype: int64

In [128]:
# required columns

req =['isbn10','title','authors','categories','thumbnail','description']
dfbook=df_book[req]

In [129]:
dfbook.dropna(inplace=True)

In [130]:
dfbook.isnull().sum()

isbn10         0
title          0
authors        0
categories     0
thumbnail      0
description    0
dtype: int64

In [131]:
dfbook

,isbn10,title,authors,categories,thumbnail,description
0,0002005883,Gilead,Marilynne Robinson,Fiction,http://books.google.com/books/content?id=KQZCP...,A NOVEL THAT READERS and critics have been eag...
1,0002261987,Spider's Web,Charles Osborne;Agatha Christie,Detective and mystery stories,http://books.google.com/books/content?id=gA5GP...,A new 'Christie for Christmas' -- a full-lengt...
2,0006163831,The One Tree,Stephen R. Donaldson,American fiction,http://books.google.com/books/content?id=OmQaw...,Volume Two of Stephen Donaldson's acclaimed se...
3,0006178731,Rage of angels,Sidney Sheldon,Fiction,http://books.google.com/books/content?id=FKo2T...,"A memorable, mesmerizing heroine Jennifer -- b..."
4,0006280897,The Four Loves,Clive Staples Lewis,Christian life,http://books.google.com/books/content?id=XhQ5X...,Lewis' work on the nature of love divides love...
...,...,...,...,...,...,...
6803,8173031010,Journey to the East,Hermann Hesse,Adventure stories,http://books.google.com/books/content?id=rq6JP...,This book tells the tale of a man who goes on ...
6804,817992162X,The Monk Who Sold His Ferrari: A Fable About F...,Robin Sharma,Health & Fitness,http://books.google.com/books/content?id=c_7mf...,"Wisdom to Create a Life of Passion, Purpose, a..."
6805,8185300534,I Am that,Sri Nisargadatta Maharaj;Sudhakar S. Dikshit,Philosophy,http://books.google.com/books/content?id=Fv_JP...,This collection of the timeless teachings of o...
6808,9027712050,The Berlin Phenomenology,Georg Wilhelm Friedrich Hegel,History,http://books.google.com/books/content?id=Vy7Sk...,Since the three volume edition ofHegel's Philo...
6809,9042003405,'I'm Telling You Stories',Helena Grice;Tim Woods,Literary Criticism,http://books.google.com/books/content?id=2lVyR...,This is a jubilant and rewarding collection of...

In [132]:
def tolist(str):
    return str.split()

In [133]:
dfbook['authors']=dfbook['authors'].apply(tolist)
dfbook['categories']=dfbook['categories'].apply(tolist)
dfbook['description']=dfbook['description'].apply(tolist)

In [134]:
dfbook

,isbn10,title,authors,categories,thumbnail,description
0,0002005883,Gilead,"[Marilynne, Robinson]",[Fiction],http://books.google.com/books/content?id=KQZCP...,"[A, NOVEL, THAT, READERS, and, critics, have, ..."
1,0002261987,Spider's Web,"[Charles, Osborne;Agatha, Christie]","[Detective, and, mystery, stories]",http://books.google.com/books/content?id=gA5GP...,"[A, new, 'Christie, for, Christmas', --, a, fu..."
2,0006163831,The One Tree,"[Stephen, R., Donaldson]","[American, fiction]",http://books.google.com/books/content?id=OmQaw...,"[Volume, Two, of, Stephen, Donaldson's, acclai..."
3,0006178731,Rage of angels,"[Sidney, Sheldon]",[Fiction],http://books.google.com/books/content?id=FKo2T...,"[A, memorable,, mesmerizing, heroine, Jennifer..."
4,0006280897,The Four Loves,"[Clive, Staples, Lewis]","[Christian, life]",http://books.google.com/books/content?id=XhQ5X...,"[Lewis', work, on, the, nature, of, love, divi..."
...,...,...,...,...,...,...
6803,8173031010,Journey to the East,"[Hermann, Hesse]","[Adventure, stories]",http://books.google.com/books/content?id=rq6JP...,"[This, book, tells, the, tale, of, a, man, who..."
6804,817992162X,The Monk Who Sold His Ferrari: A Fable About F...,"[Robin, Sharma]","[Health, &, Fitness]",http://books.google.com/books/content?id=c_7mf...,"[Wisdom, to, Create, a, Life, of, Passion,, Pu..."
6805,8185300534,I Am that,"[Sri, Nisargadatta, Maharaj;Sudhakar, S., Diks...",[Philosophy],http://books.google.com/books/content?id=Fv_JP...,"[This, collection, of, the, timeless, teaching..."
6808,9027712050,The Berlin Phenomenology,"[Georg, Wilhelm, Friedrich, Hegel]",[History],http://books.google.com/books/content?id=Vy7Sk...,"[Since, the, three, volume, edition, ofHegel's..."
6809,9042003405,'I'm Telling You Stories',"[Helena, Grice;Tim, Woods]","[Literary, Criticism]",http://books.google.com/books/content?id=2lVyR...,"[This, is, a, jubilant, and, rewarding, collec..."

In [135]:
#dfbook['title']=dfbook['title'].apply(lambda x:[i.replace(" ","") for i in x])
dfbook['authors']=dfbook['authors'].apply(lambda x:[i.replace(" ","") for i in x])
dfbook['categories']=dfbook['categories'].apply(lambda x:[i.replace(" ","") for i in x])
dfbook['description']=dfbook['description'].apply(lambda x:[i.replace(" ","") for i in x])

In [136]:
dfbook

,isbn10,title,authors,categories,thumbnail,description
0,0002005883,Gilead,"[Marilynne, Robinson]",[Fiction],http://books.google.com/books/content?id=KQZCP...,"[A, NOVEL, THAT, READERS, and, critics, have, ..."
1,0002261987,Spider's Web,"[Charles, Osborne;Agatha, Christie]","[Detective, and, mystery, stories]",http://books.google.com/books/content?id=gA5GP...,"[A, new, 'Christie, for, Christmas', --, a, fu..."
2,0006163831,The One Tree,"[Stephen, R., Donaldson]","[American, fiction]",http://books.google.com/books/content?id=OmQaw...,"[Volume, Two, of, Stephen, Donaldson's, acclai..."
3,0006178731,Rage of angels,"[Sidney, Sheldon]",[Fiction],http://books.google.com/books/content?id=FKo2T...,"[A, memorable,, mesmerizing, heroine, Jennifer..."
4,0006280897,The Four Loves,"[Clive, Staples, Lewis]","[Christian, life]",http://books.google.com/books/content?id=XhQ5X...,"[Lewis', work, on, the, nature, of, love, divi..."
...,...,...,...,...,...,...
6803,8173031010,Journey to the East,"[Hermann, Hesse]","[Adventure, stories]",http://books.google.com/books/content?id=rq6JP...,"[This, book, tells, the, tale, of, a, man, who..."
6804,817992162X,The Monk Who Sold His Ferrari: A Fable About F...,"[Robin, Sharma]","[Health, &, Fitness]",http://books.google.com/books/content?id=c_7mf...,"[Wisdom, to, Create, a, Life, of, Passion,, Pu..."
6805,8185300534,I Am that,"[Sri, Nisargadatta, Maharaj;Sudhakar, S., Diks...",[Philosophy],http://books.google.com/books/content?id=Fv_JP...,"[This, collection, of, the, timeless, teaching..."
6808,9027712050,The Berlin Phenomenology,"[Georg, Wilhelm, Friedrich, Hegel]",[History],http://books.google.com/books/content?id=Vy7Sk...,"[Since, the, three, volume, edition, ofHegel's..."
6809,9042003405,'I'm Telling You Stories',"[Helena, Grice;Tim, Woods]","[Literary, Criticism]",http://books.google.com/books/content?id=2lVyR...,"[This, is, a, jubilant, and, rewarding, collec..."

In [137]:
dfbook['tags'] = dfbook['authors']+dfbook['categories']+dfbook['description']

In [138]:
final_df= dfbook[['isbn10','title','tags']]

final_df['tags']=final_df['tags'].apply(lambda x: " ".join(x))
final_df['tags']=final_df['tags'].apply(lambda x: x.lower())

In [139]:
from nltk.stem import  PorterStemmer
ps = PorterStemmer()

In [140]:
def stem(text):
    y=[]

    for x in text.split():
        y.append(ps.stem(x))

    return " ".join(y)

In [141]:
final_df['tags'].apply(stem)

0       marilynn robinson fiction a novel that reader ...
1       charl osborne;agatha christi detect and myster...
2       stephen r. donaldson american fiction volum tw...
3       sidney sheldon fiction a memorable, mesmer her...
4       clive stapl lewi christian life lewis' work on...
                              ...
6803    hermann hess adventur stori thi book tell the ...
6804    robin sharma health & fit wisdom to creat a li...
6805    sri nisargadatta maharaj;sudhakar s. dikshit p...
6808    georg wilhelm friedrich hegel histori sinc the...
6809    helena grice;tim wood literari critic thi is a...
Name: tags, Length: 6247, dtype: str

In [174]:
idx=np.arange(0,6247)
final_df.index = idx

## Vectorisation

In [143]:
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer(max_features=5000,stop_words='english')

In [146]:
vectors=cv.fit_transform(final_df['tags'])
voctors=vectors.toarray()

In [145]:
cv.get_feature_names_out()

array(['000', '10', '100', ..., 'zone', 'zora', 'žižek'],
      shape=(5000,), dtype=object)

In [150]:
from sklearn.metrics.pairwise import cosine_similarity
simlarity=cosine_similarity(vectors)

In [151]:
simlarity[0]

array([1.        , 0.00849412, 0.02548236, ..., 0.04591336, 0.0091747 ,
       0.        ], shape=(6247,))

In [179]:
def recommend(movie):
    bookind=int(final_df[final_df['title']==movie].index[0])

    distance=simlarity[bookind]
    booklist = sorted(list(enumerate(distance)),reverse=True,key=lambda x:x[1])[1:6]

    for i in booklist:
        print(final_df.iloc[i[0]]['title'])

In [180]:
recommend('I Am that')

Psychoanalysis and Religion
Kaddish and Other Poems: 1958-1960
Introduction to Phenomenology
Art of Being
Philosophy For Dummies

In [154]:
final_df[final_df['title']=='I Am that'].index[0]

np.int64(6805)